# Generated by Django 3.2 on 2021-04-22 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dob',
            new_name='birth_date',
        ),
    ]
